import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import NavbarWidget from "@/components/widgets/Navbar";

const googleSans = Google_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.className} relative antialiased`}
      >
        <TooltipProvider>
          <NavbarWidget />
          <main className="">
            {children}
          </main>
        </TooltipProvider>
      </body>
    </html>
  );
}
